### PR TITLE
Fix-analysis-issues

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Review by nohe427 — APPROVED** [review]
LGTM!

**Comment by nohe427** [comment]
@domesticmouse - Thanks for taking a pass at this! I assume you tested that the examples still worked?

**Comment by domesticmouse** [comment]
I ran `dart test` but I didn't run the examples. I didn't see any changes by `dart fix` that should cause any issues, however.

**Comment by domesticmouse** [comment]
I can now confirm both the examples run. Added some newlines and a `flush` to make it work betterer.

**Comment by parlough** [comment]
> I can now confirm both the examples run. Added some newlines and a flush to make it work betterer.

I do love betterer things.

**Comment by nohe427** [comment]
Thanks for taking a look @domesticmouse ! Appreciate the changes!

**Pull request merged**
